apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: my-app

profiles:
  - name: dev
    deploy:
      kubectl:
        manifests:
          - deploy/dev.yaml

  - name: uat
    deploy:
      kubectl:
        manifests:
          - deploy/uat.yaml

  - name: prod
    deploy:
      kubectl:
        manifests:
          - deploy/prod.yaml
